/**
 * Apply the Season 11 ruleset to an existing DB.
 *
 *   bun run scripts/apply-s11-costs.ts                 # operates on data/cannoli.db
 *   CANNOLI_DB_PATH=/tmp/x.db bun run scripts/apply-s11-costs.ts
 *   bun run scripts/apply-s11-costs.ts --dry-run       # report, write nothing
 *
 * Two operational changes the S11 launch needs that aren't captured by the
 * roster/schedule import:
 *
 *   1. COSTS — overwrite the shared `pokemon` reference table's tier / banned /
 *      tera_banned columns from `backend/imports/Costs.xlsx` (NatDex+). S11
 *      moves to NatDex+ (legendaries / paradoxes allowed), so ~90 species flip
 *      from banned → draftable and many costs shift. Historical rosters keep
 *      their own `cost_at_draft` snapshot, so this never rewrites past seasons.
 *      Mirrors `frontend/src/data/tier-list.ts` (regenerated by
 *      `gen-tier-list.ts` from the same sheet) so the two cost authorities stay
 *      in lockstep.
 *
 *   2. LEAGUE RULES — set S11 leagues to admin-reviewed forfeits (case-by-case,
 *      not auto double-forfeit) and an 8-team playoff bracket. No-ops cleanly on
 *      a DB that hasn't launched S11 yet (e.g. the pre-launch live base).
 *
 * Idempotent: re-running converges to the same state.
 */

import { Database } from 'bun:sqlite';
import { resolve } from 'path';
import { existsSync } from 'fs';
import { parseCosts } from './parse-costs';

const DB_PATH = process.env.CANNOLI_DB_PATH || resolve(import.meta.dir, '../data/cannoli.db');
const DRY = process.argv.includes('--dry-run');

const S11_LEAGUE_IDS = ['s11-sapphire', 's11-ruby', 's11-emerald'];
const S11_FORFEIT_POLICY = 'admin_review';
const S11_PLAYOFF_TEAM_COUNT = 8;

if (!existsSync(DB_PATH)) {
  console.error(`DB not found at ${DB_PATH}.`);
  process.exit(1);
}

console.log(`\n=== Apply S11 ruleset → ${DB_PATH}${DRY ? ' (dry run)' : ''} ===`);

const db = new Database(DB_PATH);
const { byName, banned, teraBanned } = parseCosts();
console.log(
  `Costs.xlsx: ${byName.size} draftable, ${banned.length} banned, ${teraBanned.length} tera-banned`,
);

// Names the sheet references but the reference table doesn't carry — surfaced so
// a sheet rename never silently leaves a species on stale costs.
const known = new Set<string>(
  db.prepare('SELECT name FROM pokemon').all().map((r: any) => r.name),
);
const missing = [...byName.keys(), ...banned].filter((n) => !known.has(n));
if (missing.length) {
  console.warn(`\nwarning: ${missing.length} sheet name(s) absent from the pokemon table (skipped):`);
  console.warn(`   ${missing.join(', ')}`);
}

const setDraftable = db.prepare(
  'UPDATE pokemon SET tier = ?, banned = 0, tera_banned = ? WHERE name = ?',
);
const setBanned = db.prepare(
  'UPDATE pokemon SET tier = 99, banned = 1, tera_banned = 0 WHERE name = ?',
);
const setLeague = db.prepare(
  'UPDATE leagues SET forfeit_policy = ?, playoff_team_count = ? WHERE id = ?',
);

const apply = db.transaction(() => {
  let draftableChanged = 0;
  for (const e of byName.values()) {
    draftableChanged += setDraftable.run(e.tier, e.teraBanned ? 1 : 0, e.name).changes;
  }
  let bannedChanged = 0;
  for (const name of banned) {
    bannedChanged += setBanned.run(name).changes;
  }
  let leaguesChanged = 0;
  for (const id of S11_LEAGUE_IDS) {
    leaguesChanged += setLeague.run(S11_FORFEIT_POLICY, S11_PLAYOFF_TEAM_COUNT, id).changes;
  }
  return { draftableChanged, bannedChanged, leaguesChanged };
});

if (DRY) {
  console.log('\nDry run — no changes written.');
  // Show how many S11 leagues exist so the operator knows step 2 will land.
  const present = db
    .prepare(`SELECT COUNT(*) c FROM leagues WHERE id IN (${S11_LEAGUE_IDS.map(() => '?').join(',')})`)
    .get(...S11_LEAGUE_IDS) as any;
  console.log(`S11 leagues present in this DB: ${present.c}/${S11_LEAGUE_IDS.length}`);
  process.exit(0);
}

const res = apply();
db.exec('PRAGMA wal_checkpoint(TRUNCATE)');

console.log('\n=== Applied ===');
console.log(`  pokemon (draftable) rows touched: ${res.draftableChanged}`);
console.log(`  pokemon (banned)    rows touched: ${res.bannedChanged}`);
console.log(`  S11 leagues updated (forfeit=${S11_FORFEIT_POLICY}, playoff=${S11_PLAYOFF_TEAM_COUNT}): ${res.leaguesChanged}`);

// Verify the reference table matches the sheet exactly for the columns we own.
const dbBanned = (db.prepare('SELECT COUNT(*) c FROM pokemon WHERE banned = 1').get() as any).c;
const dbTeraBanned = (db.prepare('SELECT COUNT(*) c FROM pokemon WHERE tera_banned = 1').get() as any).c;
console.log(`\nReference table now: ${dbBanned} banned, ${dbTeraBanned} tera-banned`);
if (dbBanned !== banned.length) {
  console.warn(
    `warning: DB banned count (${dbBanned}) ≠ sheet (${banned.length}). Likely stale bans on species ` +
      `not present in Costs.xlsx — inspect: SELECT name FROM pokemon WHERE banned=1.`,
  );
}
