/** Short ability descriptions sourced from Pokemon Showdown data. */
export const ABILITY_DESC: Record<string, string> = {
  'Adaptability': 'Powers up same-type moves.',
  'Aftermath': 'If KOed by contact, attacker loses 1/4 max HP.',
  'Analytic': '+30% power if moving last.',
  'Anticipation': 'Alerts to super-effective or OHKO foe moves.',
  'Armor Tail': 'Blocks priority moves from foes.',
  'Blaze': '+50% Fire power below 1/3 HP.',
  'Bulletproof': 'Blocks ball and bomb moves.',
  'Cheek Pouch': 'Heals 1/3 HP when eating a berry.',
  'Chlorophyll': '2x Speed in sun.',
  'Clear Body': 'Prevents stat reduction by foes.',
  'Competitive': '+2 Sp.Atk when foe lowers stats.',
  'Compound Eyes': '+30% accuracy.',
  'Contrary': 'Inverts stat changes.',
  'Corrosion': 'Can poison Steel and Poison types.',
  'Cud Chew': 'Re-eats berry after 2 turns.',
  'Curious Medicine': 'Clears ally stat changes on switch-in.',
  'Cursed Body': '30% chance to disable attacker\'s move.',
  'Cute Charm': '30% chance to infatuate on contact.',
  'Damp': 'Prevents self-destruct and explosion.',
  'Dazzling': 'Blocks priority moves from foes.',
  'Defiant': '+2 Atk when foe lowers stats.',
  'Download': '+Atk or +Sp.Atk based on foe\'s lower defense.',
  'Drizzle': 'Sets rain on switch-in.',
  'Drought': 'Sets sun on switch-in.',
  'Dry Skin': 'Heals in rain, takes damage in sun.',
  'Electromorphosis': 'Gains charge after being hit.',
  'Flame Body': '30% chance to burn on contact.',
  'Flare Boost': '+50% Sp.Atk when burned.',
  'Flash Fire': 'Absorbs Fire moves, +50% Fire power.',
  'Flower Veil': 'Protects Grass allies from stat drops/status.',
  'Frisk': 'Reveals foe held items on switch-in.',
  'Gale Wings': 'Flying moves get +1 priority at full HP.',
  'Gluttony': 'Eats berry at 50% HP instead of 25%.',
  'Good as Gold': 'Immune to status moves.',
  'Guts': '+50% Atk when statused.',
  'Harvest': 'Restores berry each turn in sun.',
  'Healer': '30% chance to cure ally status each turn.',
  'Honey Gather': 'May gather honey after battle.',
  'Hustle': '+50% Atk, 80% physical accuracy.',
  'Hyper Cutter': 'Prevents Atk reduction.',
  'Ice Body': 'Heals 1/16 HP in hail.',
  'Illuminate': 'Prevents accuracy reduction.',
  'Illusion': 'Disguises as last party member.',
  'Immunity': 'Prevents poison.',
  'Imposter': 'Transforms into foe on switch-in.',
  'Infiltrator': 'Bypasses screens and substitutes.',
  'Inner Focus': 'Prevents flinching.',
  'Intimidate': '-1 Atk to adjacent foes on switch-in.',
  'Iron Barbs': 'Damages foes 1/8 HP on contact.',
  'Iron Fist': '+20% punch move power.',
  'Keen Eye': 'Prevents accuracy reduction.',
  'Leaf Guard': 'Prevents status in sun.',
  'Levitate': 'Immune to Ground moves.',
  'Libero': 'Changes type to match move used.',
  'Light Metal': 'Halves weight.',
  'Lightning Rod': 'Redirects Electric moves, +1 Sp.Atk.',
  'Limber': 'Prevents paralysis.',
  'Liquid Voice': 'Sound moves become Water-type.',
  'Magic Bounce': 'Reflects status moves.',
  'Magic Guard': 'Only takes damage from moves.',
  'Magician': 'Steals foe item on hit.',
  'Magnet Pull': 'Traps Steel-type foes.',
  'Marvel Scale': '+50% Def when statused.',
  'Mega Launcher': '+50% pulse move power.',
  'Mold Breaker': 'Ignores foe abilities.',
  'Moxie': '+1 Atk after KO.',
  'Multiscale': 'Halves damage at full HP.',
  'Mummy': 'Replaces foe ability on contact.',
  'Natural Cure': 'Cures status on switch-out.',
  'No Guard': 'All moves always hit.',
  'Oblivious': 'Prevents attract and Intimidate.',
  'Overcoat': 'Blocks powder moves and weather damage.',
  'Overgrow': '+50% Grass power below 1/3 HP.',
  'Own Tempo': 'Prevents confusion.',
  'Perish Body': 'Both faint in 3 turns on contact.',
  'Pickup': 'May pick up items after battle.',
  'Pixilate': 'Normal moves become Fairy-type +20%.',
  'Plus': '+50% Sp.Atk if ally has Plus/Minus.',
  'Poison Heal': 'Heals 1/8 HP from poison instead of damage.',
  'Poison Point': '30% chance to poison on contact.',
  'Poison Touch': '30% chance to poison on contact.',
  'Power of Alchemy': 'Copies fainted ally\'s ability.',
  'Prankster': 'Status moves get +1 priority.',
  'Pressure': 'Foes use extra PP.',
  'Protean': 'Changes type to match move used.',
  'Psychic Surge': 'Sets psychic terrain on switch-in.',
  'Rain Dish': 'Heals 1/16 HP in rain.',
  'Rattled': '+1 Speed when hit by Bug/Dark/Ghost.',
  'Reckless': '+20% recoil move power.',
  'Regenerator': 'Heals 1/3 HP on switch-out.',
  'Ripen': 'Doubles berry effects.',
  'Rivalry': '+25% damage against same gender.',
  'Rock Head': 'Prevents recoil damage.',
  'Rough Skin': 'Damages foes 1/8 HP on contact.',
  'Run Away': 'Guarantees escape from wild battles.',
  'Sand Spit': 'Sets sandstorm when hit.',
  'Sand Stream': 'Sets sandstorm on switch-in.',
  'Sand Veil': '+20% evasion in sandstorm.',
  'Sap Sipper': 'Absorbs Grass moves, +1 Atk.',
  'Scrappy': 'Can hit Ghost types with Normal/Fighting.',
  'Seed Sower': 'Sets grassy terrain when hit.',
  'Sharpness': '+50% slicing move power.',
  'Shed Skin': '33% chance to cure status each turn.',
  'Sheer Force': '+30% power, removes secondary effects.',
  'Shell Armor': 'Prevents critical hits.',
  'Shield Dust': 'Blocks secondary move effects.',
  'Skill Link': 'Multi-hit moves always hit max times.',
  'Slush Rush': '2x Speed in hail.',
  'Sniper': 'Critical hits deal 2.25x instead of 1.5x.',
  'Snow Cloak': '+20% evasion in hail.',
  'Solar Power': '+50% Sp.Atk in sun, loses 1/8 HP.',
  'Solid Rock': 'Reduces super-effective damage by 25%.',
  'Soundproof': 'Immune to sound moves.',
  'Speed Boost': '+1 Speed each turn.',
  'Stall': 'Always moves last.',
  'Stalwart': 'Ignores redirection.',
  'Stamina': '+1 Def when hit.',
  'Static': '30% chance to paralyze on contact.',
  'Steadfast': '+1 Speed when flinched.',
  'Sticky Hold': 'Prevents item theft.',
  'Strong Jaw': '+50% bite move power.',
  'Sturdy': 'Survives one hit at full HP with 1 HP.',
  'Supersweet Syrup': '-1 evasion to foes on switch-in.',
  'Supreme Overlord': '+10% power per fainted ally.',
  'Swarm': '+50% Bug power below 1/3 HP.',
  'Sweet Veil': 'Prevents sleep for self and allies.',
  'Swift Swim': '2x Speed in rain.',
  'Symbiosis': 'Passes item to ally when they use theirs.',
  'Synchronize': 'Passes status to attacker.',
  'Technician': '+50% power for moves with 60 or less BP.',
  'Telepathy': 'Avoids ally moves in doubles.',
  'Thermal Exchange': '+1 Atk when hit by Fire; prevents burn.',
  'Thick Fat': 'Halves Fire and Ice damage.',
  'Torrent': '+50% Water power below 1/3 HP.',
  'Tough Claws': '+33% contact move power.',
  'Trace': 'Copies foe ability on switch-in.',
  'Triage': 'Healing moves get +3 priority.',
  'Unaware': 'Ignores foe stat changes.',
  'Unburden': '2x Speed after consuming held item.',
  'Unnerve': 'Prevents foes from eating berries.',
  'Water Absorb': 'Heals 1/4 HP from Water moves.',
  'Water Bubble': '2x Water power, halves Fire damage.',
  'Weak Armor': '-1 Def, +2 Speed when hit by physical.',
  'White Smoke': 'Prevents stat reduction by foes.',
  'Wonder Skin': '50% chance to resist status moves.',
};

export function getAbilityDesc(name: string): string {
  return ABILITY_DESC[name] ?? 'No description available.';
}
