#!/bin/bash
#
# One-time setup for Showdown dev environment.
# Run: bun run setup:showdown
#
set -e

CANNOLI_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SHOWDOWN_DIR="$CANNOLI_DIR/showdown"

echo "=== Cannoli — Showdown Dev Setup ==="
echo ""

# ─── Clone repos ─────────────────────────────────────────────────────────────

if [ ! -d "$SHOWDOWN_DIR/server" ]; then
  echo "Cloning Pokemon Showdown game server..."
  git clone --depth 1 https://github.com/smogon/pokemon-showdown.git "$SHOWDOWN_DIR/server"
else
  echo "Game server already cloned."
fi

if [ ! -d "$SHOWDOWN_DIR/client" ]; then
  echo "Cloning Pokemon Showdown client..."
  git clone --depth 1 https://github.com/smogon/pokemon-showdown-client.git "$SHOWDOWN_DIR/client"
else
  echo "Client already cloned."
fi

# ─── Install game server deps ────────────────────────────────────────────────

echo "Installing game server dependencies..."
cd "$SHOWDOWN_DIR/server"
npm install --silent 2>/dev/null || npm install

# ─── Generate RSA keypair ────────────────────────────────────────────────────

if [ ! -f "$SHOWDOWN_DIR/ps_private.pem" ]; then
  echo "Generating RSA keypair..."
  openssl genrsa -out "$SHOWDOWN_DIR/ps_private.pem" 2048 2>/dev/null
  openssl rsa -in "$SHOWDOWN_DIR/ps_private.pem" -pubout -out "$SHOWDOWN_DIR/ps_public.pem" 2>/dev/null
  echo "  Keys: showdown/ps_private.pem, showdown/ps_public.pem"
else
  echo "RSA keypair already exists."
fi

# ─── Configure game server ───────────────────────────────────────────────────

echo "Configuring game server..."
PUBLIC_KEY=$(cat "$SHOWDOWN_DIR/ps_public.pem")

cat > "$SHOWDOWN_DIR/server/config/config.js" << CONFIGEOF
'use strict';

exports.port = 8000;
exports.bindaddress = '0.0.0.0';

// Login server: our Elysia backend
exports.loginserver = 'http://localhost:3001/api/ps/';
exports.loginserverpublickeyid = 4;
exports.loginserverpublickey = \`$PUBLIC_KEY\`;
exports.loginserverkeyalgo = 'RSA-SHA1';

// Replays
exports.autosavereplays = true;

// Identity
exports.routes = { root: 'localhost' };
exports.legalhosts = ['localhost', 'cannoli.localhost'];

// Not smogon
exports.pokemonshowdowncom = false;
exports.crashguard = true;
exports.reportjoins = false;
CONFIGEOF

# ─── Install chat plugin ─────────────────────────────────────────────────────

echo "Installing cannoli.ts chat plugin..."
cp "$CANNOLI_DIR/ps/cannoli.ts" "$SHOWDOWN_DIR/server/server/chat-plugins/cannoli.ts"

# ─── Configure PS client ──────────────────────────────────────────────────

echo "Configuring PS client..."

# Override client config to point at our local login server + game server
cat > "$SHOWDOWN_DIR/client/config/config.js" << 'CLIENTCFG'
var Config = Config || {};
Config.version = "0.11.2";

Config.defaultserver = {
  id: 'localhost',
  host: 'localhost',
  port: 8000,
  httpport: 8000,
  registered: true
};

Config.routes = {
  root: 'localhost',
  client: 'localhost:8080',
};

// Point at our Elysia login endpoints
Config.loginserver = 'http://localhost:3001/api/ps/';
CLIENTCFG

# testclient-key.js: point auth at ps-client-server (same-origin proxy)
# POKEMON_SHOWDOWN_TESTCLIENT_KEY must be non-empty to bypass ProxyPopup.
# The value is sent as a `sid` query param on $.post — our backend ignores it
# and uses cookies instead, so any truthy string works.
cat > "$SHOWDOWN_DIR/client/config/testclient-key.js" << 'KEYCFG'
const POKEMON_SHOWDOWN_TESTCLIENT_KEY = 'cannoli';
Config.routes = Config.routes || {};
Config.routes.client = 'localhost:8080';
KEYCFG

# Patch client.js: use http:// instead of https:// for testclient action.php
# (localhost doesn't have TLS in dev)
echo "Patching client.js for http:// in dev..."
sed -i "s|ret = 'https://' + Config.routes.client + ret;|ret = 'http://' + Config.routes.client + ret;|" \
  "$SHOWDOWN_DIR/client/play.pokemonshowdown.com/js/client.js"

echo "Building PS client (full — generates data files)..."
cd "$SHOWDOWN_DIR/client"
node build full

# ─── Bot usergroup ───────────────────────────────────────────────────────────

USERGROUPS="$SHOWDOWN_DIR/server/config/usergroups.csv"
if ! grep -q "cannolibot" "$USERGROUPS" 2>/dev/null; then
  echo "cannolibot,+" >> "$USERGROUPS"
  echo "  Added CannoliBot to usergroups."
fi

# ─── Create CannoliBot account in DB ─────────────────────────────────────────
# This happens at seed time — just note it.

# ─── Write .env for dev ──────────────────────────────────────────────────────

PRIVATE_KEY=$(cat "$SHOWDOWN_DIR/ps_private.pem")

cat > "$CANNOLI_DIR/.env" << ENVEOF
# Showdown dev config (auto-generated by setup-showdown)
PS_RSA_PRIVATE_KEY="$PRIVATE_KEY"
PS_SERVER_WS_URL=ws://localhost:8000/showdown/websocket
PS_HOSTNAME=localhost
PS_KEY_ID=4
BOT_USERNAME=CannoliBot
BOT_PASSWORD=cannolibot
VITE_SHOWDOWN_URL=http://localhost:8080?~~localhost:8000
ENVEOF

echo ""
echo "=== Setup complete ==="
echo ""
echo "Run: bun dev"
echo "  → Frontend on :5173"
echo "  → Backend on :3001 (with PS login + bot)"
echo "  → PS server on :8000"
echo "  → PS client on :8080"
echo ""
echo "Open http://localhost:5173 and navigate to Showdown tab."
echo "Play tab iframe loads http://localhost:8080"
